### ISSUE TITLE
Download all music

### ISSUE THREAD

**Issue by vbtueli** [GMMan/GroupeesDownload#12]
I'm not sure if this is possible.
So I was wondering, is it possible to download all the music I own?
Thanks.

**Comment by GMMan** [comment]
The program will favor FLAC downloads, but if you want MP3 in addition to FLAC, you can use the `--include-all` option when generating download list.

**Comment by survfate** [comment]
@GMMan is it possible to just download music / comic / others but ignore all drm-free game?

**Comment by GMMan** [comment]
Not currently
