### ISSUE TITLE
Crash on Trade Dumping

### ISSUE THREAD

**Issue by mariokinnikuman** [GMMan/GroupeesDownload#8]
4.0 release.

groupeesdownload.exe dump-trades

Auto-obtaining user ID and CSRF token...
Getting trades page 1
Getting trades page 2
Getting trade product 1/19
Getting trade product 2/19
Getting trade product 3/19
Something went wrong: AngleSharp.Dom.DomException: The string did not match the
expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope
, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelectorAll(INodeList nodes, String se
lectorText, INode scopeNode)
   at AngleSharp.Dom.Element.QuerySelectorAll(String selectors)
   at GroupeesDownload.ExtensionMethods.GetSingleByClassName(IElement self, Stri
ng name) in C:\Users\cyanic\source\repos\GroupeesDownload\GroupeesDownload\Exten
sionMethods.cs:line 13
   at GroupeesDownload.Scraper.ParseProfileSingleProduct(String html, Int32 id)
in C:\Users\cyanic\source\repos\GroupeesDownload\GroupeesDownload\Scraper.cs:lin
e 152
   at GroupeesDownload.Scraper.GetProfileSingleProduct(Int32 id) in C:\Users\cya
nic\source\repos\GroupeesDownload\GroupeesDownload\Scraper.cs:line 136
   at GroupeesDownload.Scraper.GetAllTradesCompletedProducts() in C:\Users\cyani
c\source\repos\GroupeesDownload\GroupeesDownload\Scraper.cs:line 55
   at GroupeesDownload.Program.<>c.<<Main>b__5_3>d.MoveNext() in C:\Users\cyanic
\source\repos\GroupeesDownload\GroupeesDownload\Program.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(Invocati
onContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<Bu
ildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass1
7_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass1
2_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass2
2_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass1
9_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDi
rective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass1
6_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWith
DotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8
_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by GMMan** [comment]
That's an interesting one. Does it happen every time, and if it does, can you see which one it's supposed to be? Maybe something already traded out?

**Comment by GMMan** [comment]
Ah, is it a coin? Is it clickable?

**Comment by GMMan** [comment]
OK, could you paste the link? I'll add it in as an exception.

**Comment by GMMan** [comment]
Try a few around it, see if there's anything unusual about them.

**Comment by GMMan** [comment]
That's a possibility. Does it have a different link format?

**Comment by GMMan** [comment]
I don't think this would affect anything, because it's not a trade. The dump trades command only looks at the items on the trades page.

**Comment by cyberpunkbln** [comment]
hello,
question: is it not possible to catch the error and go to the next element?
greetz

**Comment by GMMan** [comment]
Sure, but the point is for people to report the problem with the corresponding HTML so the item will actually get picked up properly.

**Comment by cyberpunkbln** [comment]
I hope i can help (i have the same error on item 33) and on this item the trade item has an $ charakter first.

```
<html><body>
<!--StartFragment-->

  | $2.5 Remute XX Amigaaaaa!
-- | --


<!--EndFragment-->
</body>
</html>[$2.5 Remute XX Amigaaaaa!](https://groupees.com/profile/purchases/3007850)
```

the others has the same error on this charakters,too i think.

Can it be? i hope:)

greetz

**Comment by GMMan** [comment]
Ah, there we go. Those ones actually link to bundles, not to products. They *should* be picked up by the original purchases page (please check), so I can just exclude them.
