### ISSUE TITLE
Consider making --include-all the default, for generate-links

### ISSUE THREAD

**Issue by seanf** [GMMan/GroupeesDownload#9]
The MP3s cost a bit of extra bandwidth/storage, but maybe it's a less surprising default.

Plus, since I turned on `--include-all`, I have found several "MP3" zips, downloaded from `*/mp3/download` URLs, which actually contained FLAC files. So far they seem to be duplicates of other FLAC zips, but it seems like there's some bad metadata in some bundles.

PS @GMMan, thanks for a great tool!

**Comment by GMMan** [comment]
By default if there's no FLAC download available, it'll take the MP3 one, so it should also cover those FLAC albums that were uploaded as MP3 before there was proper support for FLAC downloads.
